jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      password:
      username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop